name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  NOVNC_IMG: novnc
  BASE_DEVEL_IMG: base-devel
  LATEST_IMG: latest
  BASE_IMG: base

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  #test:
  #  runs-on: ubuntu-latest
  #  container:
  #    image: blackarchlinux/blackarch:base-devel

  #  steps:
  #    - uses: actions/checkout@v2

  #    - name: Run tests
  #      run: |
  #        sudo pacman -Sy --noconfirm --needed make docker devtools fakeroot fakechroot
  #        make blackarch-base
  #        make blackarch-base-devel
  #        docker build ./output/ --file ./output/Dockerfile.blackarch-base --tag $BASE_IMG
  #        docker build ./output/ --file ./output/Dockerfile.blackarch-base-devel --tag $BASE_DEVEL_IMG
  #        docker build ./blackarch-novnc --file ./blackarch-novnc/Dockerfile --tag $NOVNC_IMG
          

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    #needs: test

    runs-on: ubuntu-latest
    container:
      image: blackarchlinux/blackarch:base-devel
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: sudo pacman -Sy --noconfirm --needed make docker devtools fakeroot fakechroot

      - name: Build base
        run: |
          make blackarch-base 
          docker build ./output/ --file ./output/Dockerfile.blackarch-base --tag docker.io/ikstream/ba-docker:$BASE_IMG
          docker build ./output/ --file ./output/Dockerfile.blackarch-base --tag docker.io/ikstream/ba-docker:$LATEST_IMG
        
      - name: Build base-devel
        run: |
          make blackarch-base-devel
          docker build ./output/ --file ./output/Dockerfile.blackarch-base-devel --tag docker.io/ikstream/ba-docker:$BASE_DEVEL_IMG

      - name: Build novnc
        run: |
          docker build ./blackarch-novnc --file ./blackarch-novnc/Dockerfile --tag docker.io/ikstream/ba-docker:$NOVNC_IMG
          
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Push image
        run: |
          docker push docker.io/ikstream/ba-docker:$NOVNC_IMG
          docker push docker.io/ikstream/ba-docker:$BASE_IMG
          docker push docker.io/ikstream/ba-docker:$BASE_DEVEL_IMG
          docker push docker.io/ikstream/ba-docker:$LATEST_IMG
